name: blott_assessment
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  clock: ^1.1.1
  dio: ^5.7.0
  drift: ^2.20.3
  drift_flutter: ^0.2.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  # flutter_local_notifications: ^17.2.3
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  formz: ^0.7.0
  freezed_result: ^1.0.3+1
  gap: ^3.0.1
  get_it: ^8.0.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  permission_handler: ^11.3.1
  # url_launcher: ^6.3.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  drift_dev: ^2.20.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

flutter_gen:
  integrations:
    flutter_svg: true
